compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  glyphhanger@*:
    dependencies:
      puppeteer: "*"
  vercel@*:
    dependencies:
      esprima: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
